### ISSUE TITLE
when i use the command "kubectl exec" i got   Timeout occured

### ISSUE THREAD

**Issue by czm4514** [kubernetes-incubator/cri-containerd#439]
Kubernetes + cri-containerd+containerd setup successfully. and I created the pod using the follow pom.xml
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-example-2
spec:
  containers:
  - image: docker.io/library/nginx:latest
    name: aa
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/mast
```
after the pod is running,when i use the command "kubectl exec" i got the error
```
error: Timeout occured
```
please give me some helps.
